version: '3.8'

services:
  #Run the ETL to fetch Twitter Data
  pull_twitter:
    build: .
    container_name: twikit-container
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mongo
      - kafka
    environment:
      - MONGO_URI=mongodb://mongo:27017/twitter_etl
    stdin_open: true
    tty: true
    command: ["python", "pull_tweets.py"]  # Runs ETL script

  #Run the CDC to detect new Twitter Data and send to Kafka in Batches
  cdc_service:
    build: .
    container_name: cdc-to-kafka
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mongo
      - kafka
    environment:
      - MONGO_URI=mongodb://mongo:27017/twitter_etl
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=tweets_cdc
    command: ["python", "cdc_to_kafka.py"]  # Runs CDC script

  #Consumer for the Tweets
  kafka_consumer:
    build: .
    container_name: kafka-consumer
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=tweets_cdc
    command: ["python", "kafka_consumer.py"]  # Runs Kafka consumer script

  #Stores our Tweets Json objects
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=twitter_etl
    command: ["--wiredTigerCacheSizeGB", "0.25"]


  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

#This is for the Mongo data that I am storing on the disk
volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: none
      device: ./mongo_data
      o: bind
