version: '3.8'

services:
  pull_twitter:
    build: .
    container_name: twikit-container
    volumes:
      - .:/app  # Mounts your local directory to /app inside the container
    working_dir: /app
    depends_on:
      - mongo  # Ensures MongoDB is running before starting ETL
    environment:
      - MONGO_URI=mongodb://mongo:27017/twitter_etl
    stdin_open: true  # Keeps container interactive
    tty: true         # Allows you to attach to the container

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # Exposes MongoDB
    volumes:
      - mongo_data:/data/db  # Mounts MongoDB data persistently
    environment:
      - MONGO_INITDB_DATABASE=twitter_etl  # Creates the database on startup
    command: ["--wiredTigerCacheSizeGB", "0.25"]

volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: none
      device: ./mongo_data
      o: bind
